### ISSUE TITLE
Please add noveldrama.com website

### ISSUE THREAD

**Issue by masteoo** [martial-god/Benny-Scraper#40]

**Comment by feahnthor** [comment]
I have added the site. Instead of using your original link, it would be best to use https://noveldrama.com/virginity-in-second-marriages-bd6512.html

**Comment by masteoo** [comment]
@feahnthor thanks for support and Happy New Year! 
Do u know how can I translate long epub into Italian? I tried lots of apps but nothing works :(

**Comment by feahnthor** [comment]
> @feahnthor thanks for support and Happy New Year! Do u know how can I translate long epub into Italian? I tried lots of apps but nothing works :(

No worries and happy new years as well.

No I do not. Off the top of my head, while it is possible to do with something like the Google Translate API, Machine translations are usually pretty bad, at least that was my experience when trying Chinese machine translated novels. Your best hope is that there is someone who already made a fan translation. 

Translations will not be something I will offer as it would not be worth the cost.
